---
title: "Title"
author: "Sampanna Sharma"
date: "2020-09-29"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Required Library
```{r results = 'hide'}
library(tidyverse)
library(tidytuesdayR)
library(tidytext)
library(janitor)
library(ggbeeswarm)
library(lubridate)
library(tidymodels)
```

## Importing Data
```{r results = 'hide'}
tt <- tt_load("2020/09/29")
tt
```

```{r}
bl <- tt$beyonce_lyrics %>% clean_names()
tl <- tt$taylor_swift_lyrics %>% clean_names() %>% 
  mutate(album = str_to_title(str_trim(album)),
         artist = str_trim(artist))
sales <- tt$sales %>% clean_names()
charts <- tt$charts %>% clean_names()
```

## Cleaning

```{r}
#categorize beyonce song_id by album
# Source: https://github.com/mikemaieli/TidyTuesday/blob/master/2020_week_40/beyonceswift.r
dangerous <- c("4210083", "141844", "81345", "141846", "141847", "78135", "141848", "32796", "141849", "32869", "141850", "166809", "435484", "435491", "68426")
bday <- c("32193", "141831", "141833", "32950", "78581", "72523", "131948", "54892", "2441980", "141834")
iamsasha <- c("83613", "52158", "78577", "52683", "55885", "75936", "50873", "152213", "68973", "56878", "1829007")
four <- c("50396", "58509", "58776", "51492", "50828", "62840", "71526", "55067", "51865", "71524", "73506", "52814")
beyonce <- c("299187", "299320", "299177", "299368", "299378", "299325", "299338", "299253", "299098", "299317", "299370", "299152", "299388", "299326")
lemonade <- c("2457299", "2461219", "2461230", "2461226", "2461229", "2461236", "2461238", "2461245", "2461261", "2461233", "2461241", "2419257")

 
tl_bl <-
bl %>% 
  mutate(album = case_when(
    song_id %in% dangerous ~ "Dangrously in Love",
    song_id %in% bday ~ "B'Day",
    song_id %in% iamsasha ~ "I Am... Sasha Fierce",
    song_id %in% four ~ "4",
    song_id %in% beyonce ~ "Beyoncé",
    song_id %in% lemonade ~ "Lemonade",
  )) %>% 
  drop_na() %>%
  rename("artist" = artist_name) %>% 
  group_by(artist,album,song_name) %>% 
  summarize(lyrics = str_c(line, collapse = " ")) %>%
  ungroup() %>% 
  rbind(tl %>% select("song_name" = title,artist,lyrics,album))
```

#Sentiment of songs across time. (TODO :too manys songs, need to take popular songs)
```{r}
afinn <- get_sentiments(lexicon = "afinn")

## too many songs
tl %>% 
  unnest_tokens(word,lyrics) %>% 
  inner_join(afinn) %>% 
  group_by(title) %>% 
  mutate(num = 1:n()) %>% 
  ggplot(aes(x=num,y=value))+
  geom_line()+
  facet_wrap(~title)
```

# Distinct words across albumns of taylor swift.
```{r}
tl %>% 
  unnest_tokens(word,lyrics) %>%
  anti_join(stop_words) %>% 
  count(album,word) %>% 
  bind_tf_idf(word,album,n) %>% 
  group_by(album) %>% 
  slice_max(tf_idf,n=10,with_ties=FALSE) %>% 
  ggplot(aes(y=reorder_within(word,tf_idf,album),x=tf_idf))+
  geom_col()+
  scale_y_reordered()+
  facet_wrap(~album,scales = "free_y")
```

#violine plot of net setiment of taylor swift songs.
```{r}
tl_summary<-
tl %>% 
  unnest_tokens(word,lyrics) %>%
  anti_join(stop_words) %>% 
    left_join(afinn) %>% 
  filter(!is.na(value)) %>% 
  group_by(album,title) %>% 
  summarise(num_words = n(),
            sentiment = sum(value)) %>% 
  left_join(charts %>% 
            filter(chart == "US", artist == "Taylor Swift") %>% 
            select("album" = title,released)) %>%
  mutate(released = mdy(released))

tl_summary %>% 
  ggplot(aes(x=fct_reorder(album,released),y=sentiment))+
  geom_violin(fill = NA)+
  geom_beeswarm()+
  ggrepel::geom_text_repel(data = tl_summary %>% filter(abs(sentiment)>50),
                           aes(label = title),nudge_x = -0.3)
```

# 10 dimension of sentiment reduced to 2 dimension to find similar sentiment songs between taylor and beyonce.
```{r}
bing_sent <- get_sentiments(lexicon = "nrc")
tb_sent <-
tl_bl %>% 
  unnest_tokens(word,lyrics) %>% 
  anti_join(stop_words) %>% 
  left_join(bing_sent) %>% 
  filter(!is.na(sentiment)) %>% 
  group_by(artist,album,song_name,sentiment) %>% 
  summarise(n = n()) %>% 
  ungroup(sentiment) %>% 
  mutate(pct = n/sum(n)*100) %>% 
  ungroup() %>% 
  select(-n) %>% 
  pivot_wider(names_from = sentiment,values_from=pct,values_fill=0)
      
tb_recp <- recipe(~.,data = tb_sent) %>% 
  update_role(artist,album,song_name,new_role = "id") %>% 
  step_normalize(all_predictors()) %>% 
  step_pca(all_predictors())

tb_recp

tb_prep <- prep(tb_recp)

```


```{r}
juice(tb_prep) %>% 
  ggplot(aes(PC1,PC2,color = artist,label=song_name))+
  geom_point()+
  geom_text(check_overlap = TRUE,hjust=1,vjust=-1)+
  theme_light()
```

```{r}
library(spotifyr)
#Sys.setenv(SPOTIFY_CLIENT_ID = 'xxxxxxxxxxxxxxxxxxxxx')
#Sys.setenv(SPOTIFY_CLIENT_SECRET = 'xxxxxxxxxxxxxxxxxxxxx')

access_token <- get_spotify_access_token()

## https://juliasilge.com/blog/best-hip-hop/

pull_id <- function(query) {
  search_spotify(query, "track") %>%
    arrange(-popularity) %>%
    filter(row_number() == 1) %>%
    pull(id)
}

ids <- tl_bl %>%
  mutate(
    search_query = paste(song_name, artist),
    search_query = str_to_lower(search_query),
    search_query = str_remove(search_query, "ft.*$")
  ) %>%
  mutate(id = map_chr(search_query, possibly(pull_id, NA_character_)))

ids %>%
  select(song_name, artist, id) %>% 
  View()

features <- ids %>%
  mutate(id_group = row_number() %/% 80) %>%
  select(id_group, id) %>%
  nest(data = c(id)) %>%
  mutate(audio_features = map(data, ~ get_track_audio_features(.$id)))

features

tlbl_df <- ids %>%
  bind_cols(features %>%
    select(audio_features) %>%
    unnest(audio_features)) %>% 
  select(song_name, artist,album, lyrics, danceability:tempo) %>%
  na.omit()

```
```{r}
library(Rtsne)

tlbl_df_id <- tlbl_df[,1:4]
tlbl_df_feat <- tlbl_df[,5:15]

tsne_out <- 
tlbl_df_feat %>% 
  as.matrix() %>% 
  normalize_input() %>% 
  Rtsne(perplexity = 30,check_duplicates = FALSE)

tsne_tlbl <- 
  cbind(as_tibble(tsne_out$Y),tlbl_df_id)
  
```
#viz
```{r}
closer_circ <- function(pnts,rad,same_art){
  res <- smacpod::circles.intersect(pnts,rad)
  res <- res & (upper.tri(res) | lower.tri(res))
  #throwing closer songs of same artist
  sam <- matrix(outer(same_art,same_art,"xor"),nrow=length(same_art))
  
  res <- apply(res & sam,1,any)
  return(res)
}
#only plot song which are close proximity to another song.
tsne_tlbl_filtered <- 
  tsne_tlbl %>% 
  mutate(V1 = (V1-min(V1))/(max(V1) - min(V1)),
         V2= (V2-min(V2))/(max(V2) - min(V2)))

tsne_tlbl_filtered <- 
  tsne_tlbl_filtered %>% 
  mutate(filt = closer_circ(as.matrix(tsne_tlbl_filtered[,1:2]),
                            rad=rep(0.01,count(tsne_tlbl_filtered)),
                            same_art = (artist == "Taylor Swift")))
  
  

tsne_tlbl_filtered %>% 
  filter(filt) %>% 
  ggplot(aes(V1,V2,color=artist,label=song_name))+
  geom_point()+
  ggrepel::geom_text_repel()+
  labs(title = "Which Taylor Swift & Beyonce music sound simmilar?",
       subtitle = "Based on: danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence and tempo")+
  theme_light()
          #theme_void()
```

```{r}
     
tb_recp <- recipe(~.,data = tlbl_df) %>% 
  update_role(artist,album,song_name,lyrics,new_role = "id") %>% 
  step_normalize(all_predictors()) %>% 
  step_pca(all_predictors())

tb_recp

tb_prep <- prep(tb_recp)

```

```{r}
tidied_pca <- recipes::tidy(tb_prep,2)

tidied_pca %>% 
  filter(component %in% paste0("PC",1:6)) %>% 
  ggplot(aes(x= abs(value),y=reorder_within(terms,abs(value),component),fill = value>0))+
  geom_col()+
  scale_y_reordered()+
  facet_wrap(~ component, scales = "free_y")
```
  


```{r}
library(hrbrthemes)

juice(tb_prep) %>% 
  filter(song_name != "Love Drought",
         artist == "Beyoncé") %>%
  ggplot(aes(PC3,PC1,color = album,label=song_name))+
  geom_point(alpha=0.5,size=2)+
  geom_text(check_overlap = TRUE,hjust=1,vjust=-1)+
  annotate("text",x=0,y=5,label="Energy/Loud",size=8)+
  annotate("text",x=0,y=-8,label="Acoustic",size=8)+
  annotate("text",x=2.7,y=0,label="Dance/Joy",angle=-90,size=8)+
  annotate("text",x=-4.5,y=0,label="Tempo/Instrumental",angle=90,size=8)+
  scale_color_ipsum() +
  theme_ipsum_ps(grid = "yx")
```






